spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ayushstwt/configuration_properties.git
          clone-on-start: true
management:
  sercurity:
      enabled: false